nunit-plugin Implementation first commit
harness-community/drone-nunit pull request #1
Opened 2024-10-12 02:16 UTC by vanisrikanithi

This PR contains the nunit plugin implementation from scratch and tested this plugin successfully in Harness CI pipeline. Please find the Readme file for more information about the plugin guide.

Below is the link of tested harness pipeline link:
https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/nunit_test/pipeline-studio?storeType=INLINE

2024-10-14 13:04 UTC, franciscojuniorharness requested changes

2024-10-14 13:04 UTC, franciscojuniorharness commented on docs/conversionStyleSheet.xsl
@vanisrikanithi vanisrikanithi  Could we add a comment on the top of the file just mentioning where this file was picked from? In order to give the proper credits.

2024-10-14 13:04 UTC, franciscojuniorharness commented on plugin/plugin.go
> +			logger.Error(errMsg)
@vanisrikanithi  could we move throw the error in case of failed tests and the setting PluginFailedTestsFailBuild set to true only after processing and transform all the files? I would like to fail the execution but also have the files converted to Junit to be shown in the test results page in Harness.

2024-10-14 15:05 UTC, vanisrikanithi commented on docs/conversionStyleSheet.xsl
@franciscojuniorharness Addressed your review comment. Could you please check it once?
Note: The docs/conversionStyleSheet.xsl file have taken from the below mentioned URL from the given spec.
https://raw.githubusercontent.com/jenkinsci/nunit-plugin/refs/heads/main/src/main/resources/hudson/plugins/nunit/nunit-to-junit.xsl

2024-10-14 15:05 UTC, vanisrikanithi commented on plugin/plugin.go
> +			logger.Error(errMsg)
@franciscojuniorharness Addressed your review comment, Could you please check it once?

2024-10-14 15:11 UTC, franciscojuniorharness approved these changes
@vanisrikanithi It looks good to me. Let us wait for @Ompragash and Jamie reviews

2024-10-15 06:38 UTC, hemanthmantri commented on plugin/plugin.go
> +			return err
I think we should go ahead with parsing other files here. cc: @franciscojuniorharness @Ompragash

2024-10-15 12:34 UTC, Ompragash commented on docker/Dockerfile
> +FROM debian:bookworm
can we lock it to a specific stable version  tag [stable-20240926-slim](https://hub.docker.com/layers/library/debian/stable-20240926-slim/images/sha256-adea3605ec6fd79b351f040666f7f2a5e9ec4f93d2902c982b81e4e4231a5903?context=explore) ?

2024-10-15 12:34 UTC, Ompragash commented on docker/manifest.tmpl
> +image: plugins/nunit:{{#if build.tag}}{{trimPrefix "v" build.tag}}{{else}}latest{{/if}}
we don't need at this point, as only Linux amd64 is supported

2024-10-15 14:40 UTC, vanisrikanithi commented on docker/manifest.tmpl
> +image: plugins/nunit:{{#if build.tag}}{{trimPrefix "v" build.tag}}{{else}}latest{{/if}}
@Ompragash you mean can we delete this file permanently?

2024-10-15 15:24 UTC, vanisrikanithi commented on plugin/plugin.go
> +			return err
@franciscojuniorharness @Ompragash Could you please confirm on this?

2024-10-15 20:16 UTC, vanisrikanithi commented on docker/Dockerfile
> +FROM debian:bookworm
@Ompragash replaced with the above stable version. Could you please check and confirm?

2024-10-15 20:17 UTC, vanisrikanithi commented on docker/manifest.tmpl
> +image: plugins/nunit:{{#if build.tag}}{{trimPrefix "v" build.tag}}{{else}}latest{{/if}}
@Ompragash, I have updated it as per the comment provided. Could you please check it once?

2024-10-16 06:05 UTC, Ompragash commented on plugin/plugin.go
> +			return err
yes please, just log the error for the failed file and continue parsing the rest

2024-10-16 06:06 UTC, Ompragash commented on docker/manifest.tmpl
> +image: plugins/nunit:{{#if build.tag}}{{trimPrefix "v" build.tag}}{{else}}latest{{/if}}
yes, as we are not building a multi arc image for this, we can remove this file

2024-10-16 15:28 UTC, vanisrikanithi commented on docker/Dockerfile
> +FROM debian:bookworm
@Ompragash Could you please check and confirm?

2024-10-16 19:01 UTC, vanisrikanithi commented on plugin/plugin.go
> +			return err
@Ompragash Addressed your review comment, could you please check it once?

2024-10-16 19:02 UTC, vanisrikanithi commented on docker/manifest.tmpl
> +image: plugins/nunit:{{#if build.tag}}{{trimPrefix "v" build.tag}}{{else}}latest{{/if}}
@Ompragash removed the manifest file, could you please check it once?

2024-10-17 10:39 UTC, Ompragash reviewed
improved logging by adding log messages - please go through the code again to make similar improvements, and the rest looks good.

2024-10-17 10:39 UTC, Ompragash commented on plugin/plugin.go
> +	}
```suggestion
	var testRun TestRun
	if err := xml.NewDecoder(file).Decode(&testRun); err != nil {
		logrus.Errorf("Failed to parse test result XML file %s: %v", filePath, err)
		return false, errors.New("failed to parse test result XML")
	}
```

2024-10-17 10:39 UTC, Ompragash commented on plugin/plugin.go
> +	}
```suggestion
	file, err := os.Open(filePath)
	if err != nil {
		logrus.Errorf("Failed to open test result file %s: %v", filePath, err)
		return false, errors.New("failed to open test result file")
	}
```

2024-10-17 10:39 UTC, Ompragash commented on plugin/plugin.go
> +	}
```suggestion
func applyXSLTTransformation(filePath string, logger *logrus.Entry) error {
        // Define the path to the XSLT file (bundled within your Docker image)
        xslFilePath := "/docs/conversionStyleSheet.xsl"

        // Load the NUnit XML input
        input, err := os.ReadFile(filePath)
        if err != nil {
            logger.Errorf("Failed to read NUnit XML file %s: %v", filePath, err)
            return errors.New("failed to read NUnit XML file")
        }

        // Load the XSLT content
        xsltContent, err := os.ReadFile(xslFilePath)
        if err != nil {
            logger.Errorf("Failed to read XSLT file %s: %v", xslFilePath, err)
            return errors.New("failed to read XSLT file")
        }

        // Create a new stylesheet
        xs, err := xslt.NewStylesheet(xsltContent)
        if err != nil {
            logger.Errorf("Failed to create XSLT stylesheet: %v", err)
            return errors.New("failed to create XSLT stylesheet")
        }
        defer xs.Close() // Ensure the stylesheet is properly closed

        // Apply the XSLT transformation
        transformed, err := xs.Transform(input)
        if err != nil {
            logger.Errorf("Failed to apply XSLT transformation to file %s: %v", filePath, err)
            return errors.New("failed to apply XSLT transformation")
        }

        // Write the transformed content back to the same file
        err = os.WriteFile(filePath, transformed, 0644)
        if err != nil {
            logger.Errorf("Failed to write transformed JUnit XML to file %s: %v", filePath, err)
            return errors.New("failed to write transformed JUnit XML file")
        }
```

2024-10-17 14:33 UTC, vanisrikanithi commented on plugin/plugin.go
> +	}
@Ompragash, I Improved logging by adding log messages, could you please check and confirm?

2024-10-21 05:40 UTC, Ompragash commented on plugin/plugin.go
> +	}
`logger.Errorf` will automatically prefix the log with “Error: “, so in the log message, you can simply start with “Failed to write transformed” instead of “Error applying XSLT transformation.” please refer to the earlier review comments on the appropriate message format and use the same.

2024-10-21 13:02 UTC, Ompragash commented on plugin/plugin.go
> +	}
once the above is fixed, we are good to merge this one

2024-10-21 15:00 UTC, vanisrikanithi commented on plugin/plugin.go
> +	}
@Ompragash, I have made all the mentioned changes, could you please check and confirm them?

2024-10-21 15:19 UTC, Ompragash approved these changes

2024-10-21 15:20 UTC, merged